const mongoose = require('mongoose')

const stockSchema = new mongoose.Schema({
Symbol: String,
AssetType: String,
Name: String,
Description: String,
CIK: String,
Exchange: String,
Currency: String,
Country: String,
Sector: String,
Industry: String,
Address: String,
FiscalYearEnd: String,
LatestQuarter: String,
MarketCapitalization: String,
EBITDA: String,
PERatio: String,
PEGRatio: String,
BookValue: String,
DividendPerShare: String,
DividendYield: String,
EPS: String,
RevenuePerShareTTM: String,
ProfitMargin: String,
OperatingMarginTTM: String,
ReturnOnAssetsTTM: String,
ReturnOnEquityTTM: String,
RevenueTTM: String,
GrossProfitTTM: String,
DilutedEPSTTM: String,
QuarterlyEarningsGrowthYOY: String,
QuarterlyRevenueGrowthYOY: String,
AnalystTargetPrice: String,
TrailingPE: String,
ForwardPE: String,
PriceToSalesRatioTTM: String,
PriceToBookRatio: String,
EVToRevenue: String,
EVToEBITDA: String,
Beta: String,
'52WeekHigh': String,
'52WeekLow': String,
'50DayMovingAverage': String,
'200DayMovingAverage': String,
SharesOutstanding: String,
DividendDate: String,
ExDividendDate: String,
})

module.exports =  mongoose.model("Stock", stockSchema)